<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Cidade4Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        DB::table('cidades')->insert([

            ['nome' => 'Petrópolis', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Pinheiral', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Piraí', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Porciúncula', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Porto Real', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Quatis', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Queimados', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Quissamã', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Resende', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Rio Bonito', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Rio Claro', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Rio das Flores', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Rio das Ostras', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Rio de Janeiro', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria Madalena', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio de Pádua', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'São Fidélis', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco de Itabapoana', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'São Gonçalo', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'São João da Barra', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'São João de Meriti', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'São José de Ubá', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'São José do Vale do Rio Pret', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro da Aldeia', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Alto', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Sapucaia', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Saquarema', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Seropédica', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Silva Jardim', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Sumidouro', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Tanguá', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Teresópolis', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Trajano de Morais', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Três Rios', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Valença', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Varre-Sai', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Vassouras', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Volta Redonda', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Acari', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Açu', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Afonso Bezerra', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Água Nova', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Alexandria', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Almino Afonso', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Alto do Rodrigues', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Angicos', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Antônio Martins', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Apodi', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Areia Branca', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Arês', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Augusto Severo', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Baía Formosa', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Baraúna', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Barcelona', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Bento Fernandes', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Bodó', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Brejinho', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Caiçara do Norte', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Caiçara do Rio do Vento', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Caicó', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Campo Redondo', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Canguaretama', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Caraúbas', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Carnaúba dos Dantas', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Carnaubais', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Ceará-Mirim', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Cerro Corá', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Ezequiel', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Coronel João Pessoa', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Cruzeta', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Currais Novos', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Doutor Severiano', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Encanto', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Equador', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Espírito Santo', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Extremoz', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Felipe Guerra', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Fernando Pedroza', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Florânia', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Dantas', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Frutuoso Gomes', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Galinhos', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Goianinha', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Governador Dix-Sept Rosado', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Grossos', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Guamaré', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Ielmo Marinho', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Ipanguaçu', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Ipueira', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Itajá', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Itaú', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Jaçanã', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Jandaíra', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Janduís', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Januário Cicco', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Japi', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Jardim de Angicos', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Jardim de Piranhas', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Jardim do Seridó', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'João Câmara', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'João Dias', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'José da Penha', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Jucurutu', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Jundiá', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa d`Anta', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa de Pedras', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa de Velhos', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Nova', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Salgada', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Lajes', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Lajes Pintadas', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Lucrécia', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Luís Gomes', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Macaíba', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Macau', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Major Sales', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Marcelino Vieira', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Martins', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Maxaranguape', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Messias Targino', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Montanhas', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Monte Alegre', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Monte das Gameleiras', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Mossoró', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Natal', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Nísia Floresta', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Nova Cruz', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Olho-d`Água do Borges', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Branco', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Paraná', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Paraú', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Parazinho', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Parelhas', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Parnamirim', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Passa e Fica', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Passagem', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Patu', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Pau dos Ferros', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Grande', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Preta', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Pedro Avelino', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Pedro Velho', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Pendências', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Pilões', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Poço Branco', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Portalegre', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Porto do Mangue', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Juscelino', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Pureza', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Rafael Fernandes', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Rafael Godeiro', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Riacho da Cruz', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Riacho de Santana', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Riachuelo', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Rio do Fogo', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Rodolfo Fernandes', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Ruy Barbosa', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Matos', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Seridó', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Bento do Norte', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Bento do Trairí', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Fernando', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco do Oeste', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Gonçalo do Amarante', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São João do Sabugi', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São José de Mipibu', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São José do Campestre', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São José do Seridó', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Gostoso', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Paulo do Potengi', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Rafael', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Tomé', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'São Vicente', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Senador Elói de Souza', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Senador Georgino Avelino', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Serra de São Bento', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Serra do Mel', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Serra Negra do Norte', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Serrinha', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Serrinha dos Pintos', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Severiano Melo', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Sítio Novo', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Taboleiro Grande', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Taipu', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Tangará', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Tenente Ananias', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Tenente Laurentino Cruz', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Tibau', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Tibau do Sul', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Timbaúba dos Batistas', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Touros', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Triunfo Potiguar', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Umarizal', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Upanema', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Várzea', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Venha-Ver', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Vera Cruz', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Viçosa', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Vila Flor', 'estado_id' => '20', 'codigo_tce'  => ''],
            ['nome' => 'Aceguá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Água Santa', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Agudo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ajuricaba', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Alecrim', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Alegrete', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Alegria', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Almirante Tamandaré do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Alpestre', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Alto Alegre', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Alto Feliz', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Alvorada', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Amaral Ferrador', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ametista do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'André da Rocha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Anta Gorda', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Antônio Prado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Arambaré', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Araricá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Aratiba', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Arroio do Meio', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Arroio do Padre', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Arroio do Sal', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Arroio do Tigre', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Arroio dos Ratos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Arroio Grande', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Arvorezinha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Augusto Pestana', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Áurea', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Bagé', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Balneário Pinhal', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barão de Cotegipe', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barão do Triunfo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Guarita', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Quaraí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Ribeiro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Rio Azul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barra Funda', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barracão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Barros Cassal', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Benjamin Constant do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Bento Gonçalves', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Boa Vista das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Boa Vista do Buricá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Boa Vista do Cadeado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Boa Vista do Incra', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Boa Vista do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Bom Princípio', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Bom Progresso', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Bom Retiro do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Boqueirão do Leão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Bossoroca', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Bozano', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Braga', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Brochier', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Butiá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Caçapava do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cacequi', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeira do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeirinha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cacique Doble', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Caibaté', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Caiçara', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Camaquã', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Camargo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cambará do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Campestre da Serra', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Campina das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Campinas do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Campo Bom', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Campo Novo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Campos Borges', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Candelária', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cândido Godói', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Candiota', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Canela', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Canguçu', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Canoas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Canudos do Vale', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Capão Bonito do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Capão da Canoa', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Capão do Cipó', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Capão do Leão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Capela de Santana', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Capitão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Capivari do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Caraá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Carazinho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Carlos Barbosa', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Carlos Gomes', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Casca', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Caseiros', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Catuípe', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Caxias do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Centenário', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cerrito', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cerro Branco', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cerro Grande', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cerro Grande do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cerro Largo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Chapada', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Charqueadas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Charrua', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Chiapeta', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Chuí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Chuvisca', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cidreira', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ciríaco', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Colinas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Colorado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Condor', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Constantina', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Coqueiro Baixo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Coqueiros do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Barros', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Bicaco', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Pilar', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cotiporã', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Coxilha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Crissiumal', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cristal', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cristal do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cruz Alta', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cruzaltense', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Cruzeiro do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'David Canabarro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Derrubadas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Dezesseis de Novembro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Dilermando de Aguiar', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Dois Irmãos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Dois Irmãos das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Dois Lajeados', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Dom Feliciano', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Dom Pedrito', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Dom Pedro de Alcântara', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Dona Francisca', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Doutor Maurício Cardoso', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Doutor Ricardo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Eldorado do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Encantado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Encruzilhada do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Engenho Velho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Entre Rios do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Entre-Ijuís', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Erebango', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Erechim', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ernestina', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Erval Grande', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Erval Seco', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Esmeralda', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Esperança do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Espumoso', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Estação', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Estância Velha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Esteio', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Estrela', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Estrela Velha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Eugênio de Castro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Fagundes Varela', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Farroupilha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Faxinal do Soturno', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Faxinalzinho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Fazenda Vilanova', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Feliz', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Flores da Cunha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Floriano Peixoto', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Fontoura Xavier', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Formigueiro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Forquetinha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Fortaleza dos Valos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Frederico Westphalen', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Garibaldi', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Garruchos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Gaurama', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'General Câmara', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Gentil', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Getúlio Vargas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Giruá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Glorinha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Gramado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Gramado dos Loureiros', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Gramado Xavier', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Gravataí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Guabiju', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Guaíba', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Guaporé', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Guarani das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Harmonia', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Herval', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Herveiras', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Horizontina', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Hulha Negra', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Humaitá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ibarama', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ibiaçá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ibiraiaras', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ibirapuitã', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ibirubá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Igrejinha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ijuí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ilópolis', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Imbé', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Imigrante', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Independência', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Inhacorá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ipê', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ipiranga do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Iraí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Itaara', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Itacurubi', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Itapuca', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Itaqui', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Itati', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Itatiba do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ivorá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ivoti', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Jaboticaba', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Jacuizinho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Jacutinga', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Jaguarão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Jaguari', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Jaquirana', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Jari', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Jóia', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Júlio de Castilhos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Bonita do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa dos Três Cantos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Vermelha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Lagoão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Lajeado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Lajeado do Bugre', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Lavras do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Liberato Salzano', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Lindolfo Collor', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Linha Nova', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Maçambara', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Machadinho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Mampituba', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Manoel Viana', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Maquiné', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Maratá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Marau', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Marcelino Ramos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Mariana Pimentel', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Mariano Moro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Marques de Souza', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Mata', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Mato Castelhano', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Mato Leitão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Mato Queimado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Maximiliano de Almeida', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Minas do Leão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Miraguaí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Montauri', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Monte Alegre dos Campos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Monte Belo do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Montenegro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Mormaço', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Morrinhos do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Morro Redondo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Morro Reuter', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Mostardas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Muçum', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Muitos Capões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Muliterno', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Não-Me-Toque', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nicolau Vergueiro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nonoai', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Alvorada', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Araçá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Bassano', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Boa Vista', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Bréscia', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Candelária', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Esperança do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Hartz', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Pádua', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Palma', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Petrópolis', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Prata', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Ramada', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Roma do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Nova Santa Rita', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Novo Barreiro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Novo Cabrais', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Novo Hamburgo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Novo Machado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Novo Tiradentes', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Novo Xingu', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Osório', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Paim Filho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Palmares do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Palmeira das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Palmitinho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Panambi', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pantano Grande', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Paraí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Paraíso do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pareci Novo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Parobé', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Passa Sete', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Passo do Sobrado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Passo Fundo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Paulo Bento', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Paverama', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pedras Altas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pedro Osório', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pejuçara', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pelotas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Picada Café', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pinhal', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pinhal da Serra', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pinhal Grande', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pinheirinho do Vale', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pinheiro Machado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pirapó', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Piratini', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Planalto', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Poço das Antas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pontão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ponte Preta', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Portão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Porto Alegre', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Porto Lucena', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Porto Mauá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Porto Vera Cruz', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Porto Xavier', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Pouso Novo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Lucena', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Progresso', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Protásio Alves', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Putinga', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Quaraí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Quatro Irmãos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Quevedos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Quinze de Novembro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Redentora', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Relvado', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Restinga Seca', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Rio dos Índios', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Rio Grande', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Rio Pardo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Riozinho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Roca Sales', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Rodeio Bonito', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Rolador', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Rolante', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ronda Alta', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Rondinha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Roque Gonzales', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Rosário do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sagrada Família', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Saldanha Marinho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Salto do Jacuí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Salvador das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Salvador do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sananduva', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Bárbara do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cecília do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Clara do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Margarida do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria do Herval', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rosa', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Tereza', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santa Vitória do Palmar', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santana da Boa Vista', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Livramento', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santiago', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santo Ângelo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio da Patrulha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Palma', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Planalto', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santo Augusto', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santo Cristo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Santo Expedito do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Borja', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco de Assis', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco de Paula', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Gabriel', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Jerônimo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São João da Urtiga', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São João do Polêsine', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Jorge', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São José das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São José do Herval', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São José do Hortêncio', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São José do Inhacorá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São José do Norte', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São José do Ouro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São José do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São José dos Ausentes', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Leopoldo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Lourenço do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Luiz Gonzaga', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Marcos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Martinho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Martinho da Serra', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Nicolau', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Paulo das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro da Serra', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro do Butiá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Caí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Sepé', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Valentim', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Valentim do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Valério do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Vendelino', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'São Vicente do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sapiranga', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sapucaia do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sarandi', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Seberi', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sede Nova', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Segredo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Selbach', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Senador Salgado Filho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sentinela do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Serafina Corrêa', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sério', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sertão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sertão Santana', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sete de Setembro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Severiano de Almeida', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Silveira Martins', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sinimbu', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Sobradinho', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Soledade', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tabaí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tapejara', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tapera', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tapes', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Taquara', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Taquari', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Taquaruçu do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tavares', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tenente Portela', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Terra de Areia', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Teutônia', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tio Hugo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tiradentes do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Toropi', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Torres', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tramandaí', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Travesseiro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Três Arroios', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Três Cachoeiras', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Três Coroas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Três de Maio', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Três Forquilhas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Três Palmeiras', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Três Passos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Trindade do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Triunfo', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tucunduva', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tunas', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tupanci do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tupanciretã', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tupandi', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Tuparendi', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Turuçu', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Ubiretama', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'União da Serra', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Unistalda', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Uruguaiana', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vacaria', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vale do Sol', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vale Real', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vale Verde', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vanini', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Venâncio Aires', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vera Cruz', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Veranópolis', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vespasiano Correa', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Viadutos', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Viamão', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vicente Dutra', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Victor Graeff', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vila Flores', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vila Lângaro', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vila Maria', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vila Nova do Sul', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vista Alegre', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vista Alegre do Prata', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vista Gaúcha', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Vitória das Missões', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Westfália', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Xangri-lá', 'estado_id' => '23', 'codigo_tce'  => ''],
            ['nome' => 'Alta Floresta d`Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Alto Alegre dos Parecis', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Alto Paraíso', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Alvorada d`Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Ariquemes', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Buritis', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Cabixi', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Cacaulândia', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Cacoal', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Campo Novo de Rondônia', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Candeias do Jamari', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Castanheiras', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Cerejeiras', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Chupinguaia', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Colorado do Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Corumbiara', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Costa Marques', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Cujubim', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Espigão d`Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Governador Jorge Teixeira', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Guajará-Mirim', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Itapuã do Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Jaru', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Ji-Paraná', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Machadinho d`Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Ministro Andreazza', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Mirante da Serra', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Monte Negro', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Nova Brasilândia d`Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Nova Mamoré', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Nova União', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Novo Horizonte do Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Preto do Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Parecis', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Pimenta Bueno', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Pimenteiras do Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Porto Velho', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Médici', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Primavera de Rondônia', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Rio Crespo', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Rolim de Moura', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Santa Luzia d`Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'São Felipe d`Oeste', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco do Guaporé', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Guaporé', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Seringueiras', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Teixeirópolis', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Theobroma', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Urupá', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Vale do Anari', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Vale do Paraíso', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Vilhena', 'estado_id' => '21', 'codigo_tce'  => ''],
            ['nome' => 'Alto Alegre', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Amajari', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Boa Vista', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Bonfim', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Cantá', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Caracaraí', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Caroebe', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Iracema', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Mucajaí', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Normandia', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Pacaraima', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Rorainópolis', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'São João da Baliza', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'São Luiz', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Uiramutã', 'estado_id' => '22', 'codigo_tce'  => ''],
            ['nome' => 'Abdon Batista', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Abelardo Luz', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Agrolândia', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Agronômica', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Água Doce', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Águas de Chapecó', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Águas Frias', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Águas Mornas', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Alfredo Wagner', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Alto Bela Vista', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Anchieta', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Angelina', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Anita Garibaldi', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Anitápolis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Antônio Carlos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Apiúna', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Arabutã', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Araquari', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Araranguá', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Armazém', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Arroio Trinta', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Arvoredo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ascurra', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Atalanta', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Aurora', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Balneário Arroio do Silva', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Balneário Barra do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Balneário Camboriú', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Balneário Gaivota', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Bandeirante', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Barra Bonita', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Barra Velha', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Bela Vista do Toldo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Belmonte', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Benedito Novo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Biguaçu', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Blumenau', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Bocaina do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jardim da Serra', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus do Oeste', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Bom Retiro', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Bombinhas', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Botuverá', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Braço do Norte', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Braço do Trombudo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Brunópolis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Brusque', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Caçador', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Caibi', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Calmon', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Camboriú', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Campo Alegre', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Campo Belo do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Campo Erê', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Campos Novos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Canelinha', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Canoinhas', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Capão Alto', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Capinzal', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Capivari de Baixo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Catanduvas', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Caxambu do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Celso Ramos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Cerro Negro', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Chapadão do Lageado', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Chapecó', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Cocal do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Concórdia', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Cordilheira Alta', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Freitas', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Martins', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Correia Pinto', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Corupá', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Criciúma', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Cunha Porã', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Cunhataí', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Curitibanos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Descanso', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Dionísio Cerqueira', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Dona Emma', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Doutor Pedrinho', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Entre Rios', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ermo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Erval Velho', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Faxinal dos Guedes', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Flor do Sertão', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Florianópolis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Formosa do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Forquilhinha', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Fraiburgo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Frei Rogério', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Galvão', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Garopaba', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Garuva', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Gaspar', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Governador Celso Ramos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Grão Pará', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Gravatal', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Guabiruba', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Guaraciaba', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Guaramirim', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Guarujá do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Guatambú', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Herval d`Oeste', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ibiam', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ibicaré', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ibirama', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Içara', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ilhota', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Imaruí', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Imbituba', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Imbuia', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Indaial', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Iomerê', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ipira', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Iporã do Oeste', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ipuaçu', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ipumirim', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Iraceminha', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Irani', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Irati', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Irineópolis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Itá', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Itaiópolis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Itajaí', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Itapema', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Itapiranga', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Itapoá', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ituporanga', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Jaborá', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Jacinto Machado', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Jaguaruna', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Jaraguá do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Jardinópolis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Joaçaba', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Joinville', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'José Boiteux', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Jupiá', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Lacerdópolis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Lages', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Laguna', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Lajeado Grande', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Laurentino', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Lauro Muller', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Lebon Régis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Leoberto Leal', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Lindóia do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Lontras', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Luiz Alves', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Luzerna', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Macieira', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Mafra', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Major Gercino', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Major Vieira', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Maracajá', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Maravilha', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Marema', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Massaranduba', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Matos Costa', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Meleiro', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Mirim Doce', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Modelo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Mondaí', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Monte Carlo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Monte Castelo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Morro da Fumaça', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Morro Grande', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Navegantes', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Nova Erechim', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Nova Itaberaba', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Nova Trento', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Nova Veneza', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Novo Horizonte', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Orleans', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Otacílio Costa', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ouro', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Verde', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Paial', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Painel', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Palhoça', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Palma Sola', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Palmeira', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Palmitos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Papanduva', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Paraíso', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Passo de Torres', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Passos Maia', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Paulo Lopes', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Pedras Grandes', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Penha', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Peritiba', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Petrolândia', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Piçarras', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Pinhalzinho', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Pinheiro Preto', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Piratuba', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Planalto Alegre', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Pomerode', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ponte Alta', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ponte Alta do Norte', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Ponte Serrada', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Porto Belo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Porto União', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Pouso Redondo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Praia Grande', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Castelo Branco', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Getúlio', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Nereu', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Princesa', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Quilombo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rancho Queimado', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rio das Antas', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rio do Campo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rio do Oeste', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rio do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rio dos Cedros', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rio Fortuna', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rio Negrinho', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rio Rufino', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Riqueza', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Rodeio', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Romelândia', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Salete', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Saltinho', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Salto Veloso', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Sangão', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cecília', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Santa Helena', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rosa de Lima', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rosa do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Santa Terezinha', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Santa Terezinha do Progresso', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Santiago do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Santo Amaro da Imperatriz', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Bento do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Bernardino', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Bonifácio', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Carlos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Cristovão do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São João Batista', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São João do Itaperiú', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São João do Oeste', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São João do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Joaquim', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São José', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São José do Cedro', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São José do Cerrito', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Lourenço do Oeste', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Ludgero', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Martinho', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel da Boa Vista', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Oeste', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro de Alcântara', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Saudades', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Schroeder', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Seara', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Serra Alta', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Siderópolis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Sombrio', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Sul Brasil', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Taió', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Tangará', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Tigrinhos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Tijucas', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Timbé do Sul', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Timbó', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Timbó Grande', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Três Barras', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Treviso', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Treze de Maio', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Treze Tílias', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Trombudo Central', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Tubarão', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Tunápolis', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Turvo', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'União do Oeste', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Urubici', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Urupema', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Urussanga', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Vargeão', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Vargem', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Vargem Bonita', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Vidal Ramos', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Videira', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Vitor Meireles', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Witmarsum', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Xanxerê', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Xavantina', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Xaxim', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Zortéa', 'estado_id' => '24', 'codigo_tce'  => ''],
            ['nome' => 'Adamantina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Adolfo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Aguaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Águas da Prata', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Águas de Lindóia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Águas de Santa Bárbara', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Águas de São Pedro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Agudos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Alambari', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Alfredo Marcondes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Altair', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Altinópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Alto Alegre', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Alumínio', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Álvares Florence', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Álvares Machado', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Álvaro de Carvalho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Alvinlândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Americana', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Américo Brasiliense', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Américo de Campos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Amparo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Analândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Andradina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Angatuba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Anhembi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Anhumas', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Aparecida', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Aparecida d`Oeste', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Apiaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Araçariguama', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Araçatuba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Araçoiaba da Serra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Aramina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Arandu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Arapeí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Araraquara', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Araras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Arco-Íris', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Arealva', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Areias', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Areiópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ariranha', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Artur Nogueira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Arujá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Aspásia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Assis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Atibaia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Auriflama', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Avaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Avanhandava', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Avaré', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bady Bassitt', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Balbinos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bálsamo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bananal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Barão de Antonina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Barbosa', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bariri', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Barra Bonita', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Chapéu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Turvo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Barretos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Barrinha', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Barueri', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bastos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Batatais', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bauru', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bebedouro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bento de Abreu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bernardino de Campos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bertioga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bilac', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Birigui', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Biritiba-Mirim', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Boa Esperança do Sul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bocaina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bofete', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Boituva', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus dos Perdões', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bom Sucesso de Itararé', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Borá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Boracéia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Borborema', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Borebi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Botucatu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Bragança Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Braúna', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Brejo Alegre', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Brodowski', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Brotas', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Buri', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Buritama', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Buritizal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cabrália Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cabreúva', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Caçapava', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeira Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Caconde', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cafelândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Caiabu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Caieiras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Caiuá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cajamar', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cajati', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cajobi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cajuru', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Campina do Monte Alegre', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Campinas', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Campo Limpo Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Campos do Jordão', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Campos Novos Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cananéia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Canas', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cândido Mota', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cândido Rodrigues', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Canitar', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Capão Bonito', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Capela do Alto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Capivari', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Caraguatatuba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Carapicuíba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cardoso', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Casa Branca', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cássia dos Coqueiros', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Castilho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Catanduva', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Catiguá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cedral', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cerqueira César', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cerquilho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cesário Lange', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Charqueada', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Chavantes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Clementina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Colina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Colômbia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Conchal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Conchas', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cordeirópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Coroados', 'estado_id' => '26', 'codigo_tce'  => ''],


        ]);

    }
}
