<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Cidade5Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        DB::table('cidades')->insert([

            ['nome' => 'Coronel Macedo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Corumbataí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cosmópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cosmorama', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cotia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cravinhos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cristais Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cruzália', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cruzeiro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cubatão', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Cunha', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Descalvado', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Diadema', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Dirce Reis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Divinolândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Dobrada', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Dois Córregos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Dolcinópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Dourado', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Dracena', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Duartina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Dumont', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Echaporã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Eldorado', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Elias Fausto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Elisiário', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Embaúba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Embu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Embu-Guaçu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Emilianópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Engenheiro Coelho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Espírito Santo do Pinhal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Espírito Santo do Turvo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Estiva Gerbi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Estrela d`Oeste', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Estrela do Norte', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Euclides da Cunha Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Fartura', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Fernando Prestes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Fernandópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Fernão', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ferraz de Vasconcelos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Flora Rica', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Floreal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Flórida Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Florínia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Franca', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Morato', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Franco da Rocha', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Gabriel Monteiro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Gália', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Garça', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Gastão Vidigal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Gavião Peixoto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'General Salgado', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Getulina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Glicério', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guaiçara', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guaimbê', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guaíra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guapiaçu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guapiara', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guará', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guaraçaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guaraci', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guarani d`Oeste', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guarantã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guararapes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guararema', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guaratinguetá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guareí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guariba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guarujá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guarulhos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guatapará', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Guzolândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Herculândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Holambra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Hortolândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Iacanga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Iacri', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Iaras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ibaté', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ibirá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ibirarema', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ibitinga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ibiúna', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Icém', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Iepê', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Igaraçu do Tietê', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Igarapava', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Igaratá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Iguape', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ilha Comprida', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ilha Solteira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ilhabela', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Indaiatuba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Indiana', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Indiaporã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Inúbia Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ipaussu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Iperó', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ipeúna', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ipiguá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Iporanga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ipuã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Iracemápolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Irapuã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Irapuru', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itaberá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itajobi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itaju', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itanhaém', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itaóca', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itapecerica da Serra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itapetininga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itapeva', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itapevi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itapira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itapirapuã Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itápolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itaporanga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itapuí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itapura', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itaquaquecetuba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itararé', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itariri', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itatiba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itatinga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itirapina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itirapuã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itobi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Itupeva', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ituverava', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jaborandi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jaboticabal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jacareí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jaci', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jacupiranga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jaguariúna', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jales', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jambeiro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jandira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jardinópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jarinu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jaú', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jeriquara', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Joanópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'João Ramalho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'José Bonifácio', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Júlio Mesquita', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jumirim', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Jundiaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Junqueirópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Juquiá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Juquitiba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lagoinha', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Laranjal Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lavínia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lavrinhas', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Leme', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lençóis Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Limeira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lindóia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lins', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lorena', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lourdes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Louveira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lucélia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lucianópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Luís Antônio', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Luiziânia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lupércio', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Lutécia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Macatuba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Macaubal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Macedônia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Magda', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mairinque', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mairiporã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Manduri', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Marabá Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Maracaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Marapoama', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mariápolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Marília', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Marinópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Martinópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Matão', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mauá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mendonça', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Meridiano', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mesópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Miguelópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mineiros do Tietê', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mira Estrela', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Miracatu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mirandópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mirante do Paranapanema', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mirassol', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mirassolândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mococa', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mogi das Cruzes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mogi Guaçu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Moji Mirim', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mombuca', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Monções', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Mongaguá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Monte Alegre do Sul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Monte Alto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Monte Aprazível', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Monte Azul Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Monte Castelo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Monte Mor', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Monteiro Lobato', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Morro Agudo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Morungaba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Motuca', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Murutinga do Sul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nantes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Narandiba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Natividade da Serra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nazaré Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Neves Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nhandeara', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nipoã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Aliança', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Campina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Canaã Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Castilho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Europa', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Granada', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Guataporanga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Independência', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Luzitânia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nova Odessa', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Novais', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Novo Horizonte', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Nuporanga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ocauçu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Óleo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Olímpia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Onda Verde', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Oriente', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Orindiúva', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Orlândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Osasco', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Oscar Bressane', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Osvaldo Cruz', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ourinhos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Verde', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ouroeste', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pacaembu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Palestina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Palmares Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Palmeira d`Oeste', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Palmital', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Panorama', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Paraguaçu Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Paraibuna', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Paraíso', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Paranapanema', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Paranapuã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Parapuã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pardinho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pariquera-Açu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Parisi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Patrocínio Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Paulicéia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Paulínia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Paulistânia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Paulo de Faria', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pederneiras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Bela', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pedranópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pedregulho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pedreira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pedrinhas Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pedro de Toledo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Penápolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pereira Barreto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pereiras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Peruíbe', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Piacatu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Piedade', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pilar do Sul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pindamonhangaba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pindorama', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pinhalzinho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Piquerobi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Piquete', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Piracaia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Piracicaba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Piraju', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pirajuí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pirangi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pirapora do Bom Jesus', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pirapozinho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pirassununga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Piratininga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pitangueiras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Planalto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Platina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Poá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Poloni', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pompéia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pongaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pontal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pontalinda', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pontes Gestal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Populina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Porangaba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Porto Feliz', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Porto Ferreira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Potim', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Potirendaba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pracinha', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pradópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Praia Grande', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Pratânia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Alves', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Bernardes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Epitácio', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Prudente', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Venceslau', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Promissão', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Quadra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Quatá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Queiroz', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Queluz', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Quintana', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rafard', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rancharia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Redenção da Serra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Regente Feijó', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Reginópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Registro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Restinga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ribeira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão Bonito', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão Branco', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão Corrente', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão do Sul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão dos Índios', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão Grande', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão Pires', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão Preto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rifaina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rincão', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rinópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rio Claro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rio das Pedras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rio Grande da Serra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Riolândia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Riversul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rosana', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Roseira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rubiácea', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Rubinéia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sabino', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sagres', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sales', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sales Oliveira', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Salesópolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Salmourão', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Saltinho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Salto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Salto de Pirapora', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Salto Grande', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sandovalina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Adélia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Albertina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Bárbara d`Oeste', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Branca', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Clara d`Oeste', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz da Conceição', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz da Esperança', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz das Palmeiras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz do Rio Pardo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Ernestina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Fé do Sul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Gertrudes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Isabel', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Lúcia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria da Serra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Mercedes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita d`Oeste', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita do Passa Quatro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rosa de Viterbo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santa Salete', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santana da Ponte Pensa', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santana de Parnaíba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santo Anastácio', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santo André', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio da Alegria', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio de Posse', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Aracanguá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Jardim', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Pinhal', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santo Expedito', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santópolis do Aguapeí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Santos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Bento do Sapucaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Bernardo do Campo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Caetano do Sul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Carlos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São João da Boa Vista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São João das Duas Pontes', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São João de Iracema', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São João do Pau d`Alho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Joaquim da Barra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São José da Bela Vista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São José do Barreiro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São José do Rio Pardo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São José do Rio Preto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São José dos Campos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Lourenço da Serra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Luís do Paraitinga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Manuel', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel Arcanjo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Paulo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro do Turvo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Roque', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião da Grama', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Simão', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'São Vicente', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sarapuí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sarutaiá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sebastianópolis do Sul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Serra Azul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Serra Negra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Serrana', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sertãozinho', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sete Barras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Severínia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Silveiras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Socorro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sorocaba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sud Mennucci', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Sumaré', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Suzanápolis', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Suzano', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tabapuã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tabatinga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taboão da Serra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taciba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taguaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taiaçu', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taiúva', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tambaú', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tanabi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tapiraí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tapiratiba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taquaral', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taquaritinga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taquarituba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taquarivaí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tarabai', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tarumã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tatuí', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Taubaté', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tejupá', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Teodoro Sampaio', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Terra Roxa', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tietê', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Timburi', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Torre de Pedra', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Torrinha', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Trabiju', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tremembé', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Três Fronteiras', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tuiuti', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tupã', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Tupi Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Turiúba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Turmalina', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ubarana', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ubatuba', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Ubirajara', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Uchoa', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'União Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Urânia', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Uru', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Urupês', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Valentim Gentil', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Valinhos', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Valparaíso', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Vargem', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Vargem Grande do Sul', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Vargem Grande Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Várzea Paulista', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Vera Cruz', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Vinhedo', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Viradouro', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Vista Alegre do Alto', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Vitória Brasil', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Votorantim', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Votuporanga', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Zacarias', 'estado_id' => '26', 'codigo_tce'  => ''],
            ['nome' => 'Amparo de São Francisco', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Aquidabã', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Aracaju', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Arauá', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Areia Branca', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Barra dos Coqueiros', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Boquim', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Brejo Grande', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Campo do Brito', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Canhoba', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Canindé de São Francisco', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Capela', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Carira', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Carmópolis', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Cedro de São João', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Cristinápolis', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Cumbe', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Divina Pastora', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Estância', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Feira Nova', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Frei Paulo', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Gararu', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'General Maynard', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Gracho Cardoso', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Ilha das Flores', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Indiaroba', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Itabaiana', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Itabaianinha', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Itabi', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Itaporanga d`Ajuda', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Japaratuba', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Japoatã', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Lagarto', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Laranjeiras', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Macambira', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Malhada dos Bois', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Malhador', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Maruim', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Moita Bonita', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Monte Alegre de Sergipe', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Muribeca', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Neópolis', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Nossa Senhora Aparecida', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Nossa Senhora da Glória', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Nossa Senhora das Dores', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Nossa Senhora de Lourdes', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Nossa Senhora do Socorro', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Pacatuba', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Mole', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Pedrinhas', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Pinhão', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Pirambu', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Poço Redondo', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Poço Verde', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Porto da Folha', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Propriá', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Riachão do Dantas', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Riachuelo', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirópolis', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Rosário do Catete', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Salgado', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Santa Luzia do Itanhy', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rosa de Lima', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Santana do São Francisco', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Santo Amaro das Brotas', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'São Cristóvão', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Aleixo', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Simão Dias', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Siriri', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Telha', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Tobias Barreto', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Tomar do Geru', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Umbaúba', 'estado_id' => '25', 'codigo_tce'  => ''],
            ['nome' => 'Abreulândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Aguiarnópolis', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Aliança do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Almas', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Alvorada', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Ananás', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Angico', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Aparecida do Rio Negro', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Aragominas', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Araguacema', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Araguaçu', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Araguaína', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Araguanã', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Araguatins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Arapoema', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Arraias', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Augustinópolis', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Aurora do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Axixá do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Babaçulândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Bandeirantes do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Ouro', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Barrolândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Bernardo Sayão', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Brasilândia do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Brejinho de Nazaré', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Buriti do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeirinha', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Campos Lindos', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Cariri do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Carmolândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Carrasco Bonito', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Caseara', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Centenário', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Chapada da Natividade', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Chapada de Areia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Colinas do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Colméia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Combinado', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Conceição do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Couto de Magalhães', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Cristalândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Crixás do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Darcinópolis', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Dianópolis', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Divinópolis do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Dois Irmãos do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Dueré', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Esperantina', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Fátima', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Figueirópolis', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Filadélfia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Formoso do Araguaia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Fortaleza do Tabocão', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Goianorte', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Goiatins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Guaraí', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Gurupi', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Ipueiras', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Itacajá', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Itaguatins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Itapiratins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Itaporã do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Jaú do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Juarina', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa da Confusão', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Lajeado', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Lavandeira', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Lizarda', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Luzinópolis', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Marianópolis do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Mateiros', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Maurilândia do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Miracema do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Miranorte', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Monte do Carmo', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Monte Santo do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Muricilândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Natividade', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Nazaré', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Nova Olinda', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Nova Rosalândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Novo Acordo', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Novo Alegre', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Novo Jardim', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Oliveira de Fátima', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Palmas', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Palmeirante', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Palmeiras do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Palmeirópolis', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Paraíso do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Paranã', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Pau d`Arco', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Pedro Afonso', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Peixe', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Pequizeiro', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Pindorama do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Piraquê', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Pium', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Ponte Alta do Bom Jesus', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Ponte Alta do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Porto Alegre do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Porto Nacional', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Praia Norte', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Kennedy', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Pugmil', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Recursolândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Riachinho', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Rio da Conceição', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Rio dos Bois', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Rio Sono', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Sampaio', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Sandolândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Santa Fé do Araguaia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rosa do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Santa Tereza do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Santa Terezinha do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'São Bento do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'São Félix do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'São Salvador do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'São Valério da Natividade', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Silvanópolis', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Sítio Novo do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Sucupira', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Taguatinga', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Taipas do Tocantins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Talismã', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Tocantínia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Tocantinópolis', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Tupirama', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Tupiratins', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Wanderlândia', 'estado_id' => '27', 'codigo_tce'  => ''],
            ['nome' => 'Xambioá', 'estado_id' => '27', 'codigo_tce'  => ''],


        ]);

    }
}
