<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Cidade3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        DB::table('cidades')->insert([

            ['nome' => 'Conceição do Araguaia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Concórdia do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Cumaru do Norte', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Curionópolis', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Curralinho', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Curuá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Curuçá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Dom Eliseu', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Eldorado dos Carajás', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Faro', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Floresta do Araguaia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Garrafão do Norte', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Goianésia do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Gurupá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Igarapé-Açu', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Igarapé-Miri', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Inhangapi', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Ipixuna do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Irituia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Itaituba', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Itupiranga', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Jacareacanga', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Jacundá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Juruti', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Limoeiro do Ajuru', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Mãe do Rio', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Magalhães Barata', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Marabá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Maracanã', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Marapanim', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Marituba', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Medicilândia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Melgaço', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Mocajuba', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Moju', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Monte Alegre', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Muaná', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Nova Esperança do Piriá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Nova Ipixuna', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Nova Timboteua', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Novo Progresso', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Novo Repartimento', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Óbidos', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Oeiras do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Oriximiná', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Ourém', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Ourilândia do Norte', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Pacajá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Palestina do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Paragominas', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Parauapebas', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Pau d`Arco', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Peixe-Boi', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Piçarra', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Placas', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Ponta de Pedras', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Portel', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Porto de Moz', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Prainha', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Primavera', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Quatipuru', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Redenção', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Rio Maria', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Rondon do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Rurópolis', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Salinópolis', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Salvaterra', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santa Bárbara do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz do Arari', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santa Isabel do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santa Luzia do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria das Barreiras', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Araguaia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santarém', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santarém Novo', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Tauá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São Caetano de Odivelas', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos do Araguaia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos do Capim', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São Félix do Xingu', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São Geraldo do Araguaia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São João da Ponta', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São João de Pirabas', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São João do Araguaia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Guamá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião da Boa Vista', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Sapucaia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Senador José Porfírio', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Soure', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Tailândia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Terra Alta', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Terra Santa', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Tomé-Açu', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Tracuateua', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Trairão', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Tucumã', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Tucuruí', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Ulianópolis', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Uruará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Vigia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Viseu', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Vitória do Xingu', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Xinguara', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Água Branca', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Aguiar', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Alagoa Grande', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Alagoa Nova', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Alagoinha', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Alcantil', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Algodão de Jandaíra', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Alhandra', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Amparo', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Aparecida', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Araçagi', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Arara', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Araruna', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Areia', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Areia de Baraúnas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Areial', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Aroeiras', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Assunção', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Baía da Traição', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Bananeiras', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Baraúna', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Barra de Santa Rosa', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Barra de Santana', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Barra de São Miguel', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Bayeux', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Belém', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Belém do Brejo do Cruz', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Bernardino Batista', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Boa Ventura', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Boa Vista', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Bom Sucesso', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Bonito de Santa Fé', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Boqueirão', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Borborema', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Brejo do Cruz', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Brejo dos Santos', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Caaporã', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cabaceiras', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cabedelo', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeira dos Índios', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cacimba de Areia', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cacimba de Dentro', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cacimbas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Caiçara', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cajazeiras', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cajazeirinhas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Caldas Brandão', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Camalaú', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Campina Grande', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Campo de Santana', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Capim', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Caraúbas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Carrapateira', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Casserengue', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Catingueira', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Catolé do Rocha', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Caturité', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Conceição', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Condado', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Conde', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Congo', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Coremas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Coxixola', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cruz do Espírito Santo', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cubati', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cuité', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cuité de Mamanguape', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Cuitegi', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Curral de Cima', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Curral Velho', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Damião', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Desterro', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Diamante', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Dona Inês', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Duas Estradas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Emas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Esperança', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Fagundes', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Frei Martinho', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Gado Bravo', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Guarabira', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Gurinhém', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Gurjão', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Ibiara', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Igaracy', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Imaculada', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Ingá', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Itabaiana', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Itaporanga', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Itapororoca', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Itatuba', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Jacaraú', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Jericó', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'João Pessoa', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Juarez Távora', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Juazeirinho', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Junco do Seridó', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Juripiranga', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Juru', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa de Dentro', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Seca', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Lastro', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Livramento', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Logradouro', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Lucena', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Mãe d`Água', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Malta', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Mamanguape', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Manaíra', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Marcação', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Mari', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Marizópolis', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Massaranduba', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Mataraca', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Matinhas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Mato Grosso', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Maturéia', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Mogeiro', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Montadas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Monte Horebe', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Monteiro', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Mulungu', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Natuba', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Nazarezinho', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Nova Floresta', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Nova Olinda', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Nova Palmeira', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Olho d`Água', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Olivedos', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Velho', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Parari', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Passagem', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Patos', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Paulista', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Branca', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Lavrada', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pedras de Fogo', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pedro Régis', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Piancó', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Picuí', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pilar', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pilões', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pilõezinhos', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pirpirituba', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pitimbu', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pocinhos', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Poço Dantas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Poço de José de Moura', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Pombal', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Prata', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Princesa Isabel', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Puxinanã', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Queimadas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Quixabá', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Remígio', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Riachão', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Riachão do Bacamarte', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Riachão do Poço', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Riacho de Santo Antônio', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Riacho dos Cavalos', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Rio Tinto', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Salgadinho', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Salgado de São Félix', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cecília', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santa Helena', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santa Inês', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santa Luzia', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santa Teresinha', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santana de Mangueira', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santana dos Garrotes', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santarém', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Santo André', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São Bentinho', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São Bento', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos de Pombal', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos do Cariri', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São João do Cariri', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São João do Rio do Peixe', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São João do Tigre', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José da Lagoa Tapada', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José de Caiana', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José de Espinharas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José de Piranhas', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José de Princesa', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José do Bonfim', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José do Brejo do Cruz', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José do Sabugi', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José dos Cordeiros', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São José dos Ramos', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São Mamede', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel de Taipu', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião de Lagoa de Roça', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Umbuzeiro', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Sapé', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Seridó', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Serra Branca', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Serra da Raiz', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Serra Grande', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Serra Redonda', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Serraria', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Sertãozinho', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Sobrado', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Solânea', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Soledade', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Sossêgo', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Sousa', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Sumé', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Taperoá', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Tavares', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Teixeira', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Tenório', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Triunfo', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Uiraúna', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Umbuzeiro', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Várzea', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Vieirópolis', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Vista Serrana', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Zabelê', 'estado_id' => '15', 'codigo_tce'  => ''],
            ['nome' => 'Abatiá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Adrianópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Agudos do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Almirante Tamandaré', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Altamira do Paraná', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Alto Paraíso', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Alto Paraná', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Alto Piquiri', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Altônia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Alvorada do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Amaporã', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ampére', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Anahy', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Andirá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ângulo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Antonina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Antônio Olinto', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Apucarana', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Arapongas', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Arapoti', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Arapuã', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Araruna', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Araucária', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ariranha do Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Assaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Assis Chateaubriand', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Astorga', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Atalaia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Balsa Nova', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Bandeirantes', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Barbosa Ferraz', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Jacaré', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Barracão', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Bela Vista da Caroba', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Bela Vista do Paraíso', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Bituruna', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Boa Esperança', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Boa Esperança do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Boa Ventura de São Roque', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Boa Vista da Aparecida', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Bocaiúva do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Bom Sucesso', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Bom Sucesso do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Borrazópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Braganey', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Brasilândia do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cafeara', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cafelândia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cafezal do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Califórnia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cambará', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cambé', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cambira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Campina da Lagoa', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Campina do Simão', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Campina Grande do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Campo Bonito', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Campo do Tenente', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Campo Largo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Campo Magro', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Campo Mourão', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cândido de Abreu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Candói', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cantagalo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Capanema', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Capitão Leônidas Marques', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Carambeí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Carlópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cascavel', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Castro', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Catanduvas', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Centenário do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cerro Azul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Céu Azul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Chopinzinho', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cianorte', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cidade Gaúcha', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Clevelândia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Colombo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Colorado', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Congonhinhas', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Conselheiro Mairinck', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Contenda', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Corbélia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cornélio Procópio', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Domingos Soares', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Vivida', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Corumbataí do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cruz Machado', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cruzeiro do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cruzeiro do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cruzeiro do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Cruzmaltina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Curitiba', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Curiúva', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Diamante d`Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Diamante do Norte', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Diamante do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Dois Vizinhos', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Douradina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Doutor Camargo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Doutor Ulysses', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Enéas Marques', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Engenheiro Beltrão', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Entre Rios do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Esperança Nova', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Espigão Alto do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Farol', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Faxinal', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Fazenda Rio Grande', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Fênix', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Fernandes Pinheiro', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Figueira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Flor da Serra do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Floraí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Floresta', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Florestópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Flórida', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Formosa do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Foz do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Foz do Jordão', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Alves', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Beltrão', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'General Carneiro', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Godoy Moreira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Goioerê', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Goioxim', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Grandes Rios', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guaíra', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guairaçá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guamiranga', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guapirama', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guaporema', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guaraci', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guaraniaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guarapuava', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guaraqueçaba', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Guaratuba', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Honório Serpa', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ibaiti', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ibema', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ibiporã', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Icaraíma', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Iguaraçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Iguatu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Imbaú', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Imbituva', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Inácio Martins', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Inajá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Indianópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ipiranga', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Iporã', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Iracema do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Irati', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Iretama', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Itaguajé', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Itaipulândia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Itambaracá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Itambé', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Itapejara d`Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Itaperuçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Itaúna do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ivaiporã', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ivaté', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ivatuba', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jaboti', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jacarezinho', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jaguapitã', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jaguariaíva', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jandaia do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Janiópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Japira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Japurá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jardim Alegre', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jardim Olinda', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jataizinho', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jesuítas', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Joaquim Távora', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jundiaí do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Juranda', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Jussara', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Kaloré', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Lapa', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Laranjal', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Laranjeiras do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Leópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Lidianópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Lindoeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Loanda', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Lobato', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Londrina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Luiziana', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Lunardelli', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Lupionópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mallet', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mamborê', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mandaguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mandaguari', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mandirituba', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Manfrinópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mangueirinha', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Manoel Ribas', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Marechal Cândido Rondon', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Maria Helena', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Marialva', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Marilândia do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Marilena', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mariluz', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Maringá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mariópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Maripá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Marmeleiro', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Marquinho', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Marumbi', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Matelândia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Matinhos', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mato Rico', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mauá da Serra', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Medianeira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mercedes', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Mirador', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Miraselva', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Missal', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Moreira Sales', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Morretes', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Munhoz de Melo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nossa Senhora das Graças', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Aliança do Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova América da Colina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Aurora', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Cantu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Esperança', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Esperança do Sudoeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Fátima', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Laranjeiras', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Londrina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Olímpia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Prata do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Santa Bárbara', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Santa Rosa', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Nova Tebas', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Novo Itacolomi', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ortigueira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ourizona', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Verde do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Paiçandu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Palmas', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Palmeira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Palmital', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Palotina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Paraíso do Norte', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Paranacity', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Paranaguá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Paranapoema', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Paranavaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pato Bragado', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pato Branco', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Paula Freitas', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Paulo Frontin', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Peabiru', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Perobal', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pérola', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pérola d`Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Piên', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pinhais', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pinhal de São Bento', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pinhalão', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pinhão', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Piraí do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Piraquara', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pitanga', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pitangueiras', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Planaltina do Paraná', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Planalto', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ponta Grossa', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pontal do Paraná', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Porecatu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Porto Amazonas', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Porto Barreiro', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Porto Rico', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Porto Vitória', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Prado Ferreira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Pranchita', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Castelo Branco', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Primeiro de Maio', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Prudentópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Quarto Centenário', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Quatiguá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Quatro Barras', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Quatro Pontes', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Quedas do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Querência do Norte', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Quinta do Sol', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Quitandinha', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ramilândia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rancho Alegre', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rancho Alegre d`Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Realeza', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rebouças', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Renascença', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Reserva', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Reserva do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão Claro', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão do Pinhal', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rio Azul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rio Bom', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rio Bonito do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rio Branco do Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rio Branco do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rio Negro', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rolândia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Roncador', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rondon', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Rosário do Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Sabáudia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Salgado Filho', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Salto do Itararé', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Salto do Lontra', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Amélia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cecília do Pavão', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz de Monte Castelo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Fé', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Helena', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Inês', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Isabel do Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Izabel do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Lúcia', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Mariana', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Mônica', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Tereza do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santa Terezinha de Itaipu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Itararé', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio da Platina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Caiuá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Paraíso', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Sudoeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Santo Inácio', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Carlos do Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Jerônimo da Serra', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São João', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São João do Caiuá', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São João do Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São João do Triunfo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Jorge d`Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Jorge do Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Jorge do Patrocínio', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São José da Boa Vista', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São José das Palmeiras', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São José dos Pinhais', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Manoel do Paraná', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Mateus do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro do Ivaí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro do Paraná', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião da Amoreira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'São Tomé', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Sapopema', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Sarandi', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Saudade do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Sengés', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Serranópolis do Iguaçu', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Sertaneja', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Sertanópolis', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Siqueira Campos', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Sulina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tamarana', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tamboara', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tapejara', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tapira', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Teixeira Soares', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Telêmaco Borba', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Terra Boa', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Terra Rica', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Terra Roxa', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tibagi', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tijucas do Sul', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Toledo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tomazina', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Três Barras do Paraná', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tunas do Paraná', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tuneiras do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Tupãssi', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Turvo', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ubiratã', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Umuarama', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'União da Vitória', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Uniflor', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Uraí', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Ventania', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Vera Cruz do Oeste', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Verê', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Virmond', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Vitorino', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Wenceslau Braz', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Xambrê', 'estado_id' => '18', 'codigo_tce'  => ''],
            ['nome' => 'Abreu e Lima', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Afogados da Ingazeira', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Afrânio', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Agrestina', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Água Preta', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Águas Belas', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Alagoinha', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Aliança', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Altinho', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Amaraji', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Angelim', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Araçoiaba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Araripina', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Arcoverde', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Barra de Guabiraba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Barreiros', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Belém de Maria', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Belém de São Francisco', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Belo Jardim', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Betânia', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Bezerros', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Bodocó', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Bom Conselho', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jardim', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Bonito', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Brejão', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Brejinho', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Brejo da Madre de Deus', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Buenos Aires', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Buíque', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Cabo de Santo Agostinho', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Cabrobó', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeirinha', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Caetés', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Calçado', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Calumbi', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Camaragibe', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Camocim de São Félix', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Camutanga', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Canhotinho', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Capoeiras', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Carnaíba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Carnaubeira da Penha', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Carpina', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Caruaru', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Casinhas', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Catende', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Cedro', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Chã de Alegria', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Chã Grande', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Condado', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Correntes', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Cortês', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Cumaru', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Cupira', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Custódia', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Dormentes', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Escada', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Exu', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Feira Nova', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Fernando de Noronha', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Ferreiros', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Flores', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Floresta', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Frei Miguelinho', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Gameleira', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Garanhuns', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Glória do Goitá', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Goiana', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Granito', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Gravatá', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Iati', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Ibimirim', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Ibirajuba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Igarassu', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Iguaraci', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Ilha de Itamaracá', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Inajá', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Ingazeira', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Ipojuca', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Ipubi', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Itacuruba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Itaíba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Itambé', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Itapetim', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Itapissuma', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Itaquitinga', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Jaboatão dos Guararapes', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Jaqueira', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Jataúba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Jatobá', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'João Alfredo', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Joaquim Nabuco', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Jucati', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Jupi', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Jurema', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa do Carro', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa do Itaenga', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa do Ouro', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa dos Gatos', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Grande', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Lajedo', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Limoeiro', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Macaparana', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Machados', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Manari', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Maraial', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Mirandiba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Moreilândia', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Moreno', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Nazaré da Mata', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Olinda', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Orobó', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Orocó', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Ouricuri', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Palmares', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Palmeirina', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Panelas', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Paranatama', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Parnamirim', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Passira', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Paudalho', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Paulista', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Pedra', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Pesqueira', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Petrolândia', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Petrolina', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Poção', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Pombos', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Primavera', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Quipapá', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Quixaba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Recife', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Riacho das Almas', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Rio Formoso', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Sairé', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Salgadinho', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Salgueiro', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Saloá', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Sanharó', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz da Baixa Verde', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz do Capibaribe', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Santa Filomena', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria da Boa Vista', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria do Cambucá', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Santa Terezinha', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São Benedito do Sul', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São Bento do Una', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São Caitano', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São João', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São Joaquim do Monte', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São José da Coroa Grande', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São José do Belmonte', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São José do Egito', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São Lourenço da Mata', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'São Vicente Ferrer', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Serra Talhada', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Serrita', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Sertânia', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Sirinhaém', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Solidão', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Surubim', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Tabira', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Tacaimbó', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Tacaratu', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Tamandaré', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Taquaritinga do Norte', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Terezinha', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Terra Nova', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Timbaúba', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Toritama', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Tracunhaém', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Trindade', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Triunfo', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Tupanatinga', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Tuparetama', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Venturosa', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Verdejante', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Vertente do Lério', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Vertentes', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Vicência', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Vitória de Santo Antão', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Xexéu', 'estado_id' => '16', 'codigo_tce'  => ''],
            ['nome' => 'Acauã', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Agricolândia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Água Branca', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Alagoinha do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Alegrete do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Alto Longá', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Altos', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Alvorada do Gurguéia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Amarante', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Angical do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Anísio de Abreu', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Antônio Almeida', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Aroazes', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Aroeiras do Itaim', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Arraial', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Assunção do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Avelino Lopes', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Baixa Grande do Ribeiro', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Barra d`Alcântara', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Barras', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Barreiras do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Barro Duro', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Batalha', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Bela Vista do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Belém do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Beneditinos', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Bertolínia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Betânia do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Boa Hora', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Bocaina', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Bom Princípio do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Bonfim do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Boqueirão do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Brasileira', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Brejo do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Buriti dos Lopes', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Buriti dos Montes', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Cabeceiras do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Cajazeiras do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Cajueiro da Praia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Caldeirão Grande do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Campinas do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Campo Alegre do Fidalgo', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Campo Grande do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Campo Largo do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Campo Maior', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Canavieira', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Canto do Buriti', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Capitão de Campos', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Capitão Gervásio Oliveira', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Caracol', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Caraúbas do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Caridade do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Castelo do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Caxingó', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Cocal', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Cocal de Telha', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Cocal dos Alves', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Coivaras', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Colônia do Gurguéia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Colônia do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Conceição do Canindé', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Coronel José Dias', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Corrente', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Cristalândia do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Cristino Castro', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Curimatá', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Currais', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Curral Novo do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Curralinhos', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Demerval Lobão', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Dirceu Arcoverde', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Dom Expedito Lopes', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Dom Inocêncio', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Domingos Mourão', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Elesbão Veloso', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Eliseu Martins', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Esperantina', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Fartura do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Flores do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Floresta do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Floriano', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Francinópolis', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Ayres', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Macedo', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Santos', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Fronteiras', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Geminiano', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Gilbués', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Guadalupe', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Guaribas', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Hugo Napoleão', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Ilha Grande', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Inhuma', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Ipiranga do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Isaías Coelho', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Itainópolis', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Itaueira', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Jacobina do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Jaicós', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Jardim do Mulato', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Jatobá do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Jerumenha', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'João Costa', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Joaquim Pires', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Joca Marques', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'José de Freitas', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Juazeiro do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Júlio Borges', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Jurema', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Alegre', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa de São Francisco', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa do Barro do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa do Sítio', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Lagoinha do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Landri Sales', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Luís Correia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Luzilândia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Madeiro', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Manoel Emídio', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Marcolândia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Marcos Parente', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Massapê do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Matias Olímpio', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Miguel Alves', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Miguel Leão', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Milton Brandão', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Monsenhor Gil', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Monsenhor Hipólito', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Monte Alegre do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Morro Cabeça no Tempo', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Morro do Chapéu do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Murici dos Portelas', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Nazaré do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Nossa Senhora de Nazaré', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Nossa Senhora dos Remédios', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Nova Santa Rita', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Novo Oriente do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Novo Santo Antônio', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Oeiras', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Olho d`Água do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Padre Marcos', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Paes Landim', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Pajeú do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Palmeira do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Palmeirais', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Paquetá', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Parnaguá', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Parnaíba', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Passagem Franca do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Patos do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Pau d`Arco do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Paulistana', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Pavussu', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Pedro II', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Pedro Laurentino', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Picos', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Pimenteiras', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Pio IX', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Piracuruca', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Piripiri', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Porto', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Porto Alegre do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Prata do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Queimada Nova', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Redenção do Gurguéia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Regeneração', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Riacho Frio', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Ribeira do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Ribeiro Gonçalves', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Rio Grande do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz dos Milagres', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Santa Filomena', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Santa Luz', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rosa do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio de Lisboa', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio dos Milagres', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Santo Inácio do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Braz do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Félix do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco de Assis do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Gonçalo do Gurguéia', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Gonçalo do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São João da Canabrava', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São João da Fronteira', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São João da Serra', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São João da Varjota', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São João do Arraial', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São João do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São José do Divino', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São José do Peixe', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São José do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Julião', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Lourenço do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Luis do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel da Baixa Grande', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Fidalgo', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Tapuio', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'São Raimundo Nonato', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Sebastião Barros', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Sebastião Leal', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Sigefredo Pacheco', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Simões', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Simplício Mendes', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Socorro do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Sussuapara', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Tamboril do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Tanque do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Teresina', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'União', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Uruçuí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Valença do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Várzea Branca', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Várzea Grande', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Vera Mendes', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Vila Nova do Piauí', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Wall Ferraz', 'estado_id' => '17', 'codigo_tce'  => ''],
            ['nome' => 'Angra dos Reis', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Aperibé', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Araruama', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Areal', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Armação dos Búzios', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Arraial do Cabo', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Piraí', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Barra Mansa', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Belford Roxo', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jardim', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus do Itabapoana', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Cabo Frio', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeiras de Macacu', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Cambuci', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Campos dos Goytacazes', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Cantagalo', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Carapebus', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Cardoso Moreira', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Carmo', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Casimiro de Abreu', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Comendador Levy Gasparian', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Conceição de Macabu', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Cordeiro', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Duas Barras', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Duque de Caxias', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Engenheiro Paulo de Frontin', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Guapimirim', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Iguaba Grande', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Itaboraí', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Itaguaí', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Italva', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Itaocara', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Itaperuna', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Itatiaia', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Japeri', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Laje do Muriaé', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Macaé', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Macuco', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Magé', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Mangaratiba', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Maricá', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Mendes', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Mesquita', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Miguel Pereira', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Miracema', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Natividade', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Nilópolis', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Niterói', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Nova Friburgo', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Nova Iguaçu', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Paracambi', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Paraíba do Sul', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Parati', 'estado_id' => '19', 'codigo_tce'  => ''],
            ['nome' => 'Paty do Alferes', 'estado_id' => '19', 'codigo_tce'  => ''],


        ]);

    }
}
