<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Cidade2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        DB::table('cidades')->insert([

            ['nome' => 'Pio XII', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Pirapemas', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Poção de Pedras', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Porto Franco', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Porto Rico do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Dutra', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Juscelino', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Médici', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Sarney', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Vargas', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Primeira Cruz', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Raposa', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Riachão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Ribamar Fiquene', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Rosário', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Sambaíba', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santa Filomena do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santa Helena', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santa Inês', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santa Luzia', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santa Luzia do Paruá', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santa Quitéria do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santo Amaro do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio dos Lopes', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Benedito do Rio Preto', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Bento', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Bernardo', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos do Azeitão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Félix de Balsas', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco do Brejão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São João Batista', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São João do Carú', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São João do Paraíso', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São João do Soter', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São João dos Patos', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São José de Ribamar', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São José dos Basílios', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Luís', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Luís Gonzaga do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Mateus do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro da Água Branca', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro dos Crentes', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Raimundo das Mangabeiras', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Raimundo do Doca Bezerra', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Roberto', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'São Vicente Ferrer', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Satubinha', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Senador Alexandre Costa', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Senador La Rocque', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Serrano do Maranhão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Sítio Novo', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Sucupira do Norte', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Sucupira do Riachão', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Tasso Fragoso', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Timbiras', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Timon', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Trizidela do Vale', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Tufilândia', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Tuntum', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Turiaçu', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Turilândia', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Tutóia', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Urbano Santos', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Vargem Grande', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Viana', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Vila Nova dos Martírios', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Vitória do Mearim', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Vitorino Freire', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Zé Doca', 'estado_id' => '10', 'codigo_tce'  => ''],
            ['nome' => 'Acorizal', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Água Boa', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Alta Floresta', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Alto Araguaia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Alto Boa Vista', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Alto Garças', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Alto Paraguai', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Alto Taquari', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Apiacás', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Araguaiana', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Araguainha', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Araputanga', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Arenápolis', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Aripuanã', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Barão de Melgaço', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Bugres', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Barra do Garças', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus do Araguaia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Brasnorte', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Cáceres', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Campinápolis', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Campo Novo do Parecis', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Campo Verde', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Campos de Júlio', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Canabrava do Norte', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Canarana', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Carlinda', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Castanheira', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Chapada dos Guimarães', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Cláudia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Cocalinho', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Colíder', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Colniza', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Comodoro', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Confresa', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Conquista d`Oeste', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Cotriguaçu', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Cuiabá', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Curvelândia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Curvelândia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Denise', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Diamantino', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Dom Aquino', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Feliz Natal', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Figueirópolis d`Oeste', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Gaúcha do Norte', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'General Carneiro', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Glória d`Oeste', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Guarantã do Norte', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Guiratinga', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Indiavaí', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Ipiranga do Norte', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Itanhangá', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Itaúba', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Itiquira', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Jaciara', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Jangada', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Jauru', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Juara', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Juína', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Juruena', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Juscimeira', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Lambari d`Oeste', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Lucas do Rio Verde', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Luciára', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Marcelândia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Matupá', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Mirassol d`Oeste', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nobres', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nortelândia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nossa Senhora do Livramento', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Bandeirantes', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Brasilândia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Canaã do Norte', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Guarita', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Lacerda', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Marilândia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Maringá', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Monte verde', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Mutum', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Olímpia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Santa Helena', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Ubiratã', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Nova Xavantina', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Novo Horizonte do Norte', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Novo Mundo', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Novo Santo Antônio', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Novo São Joaquim', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Paranaíta', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Paranatinga', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Preta', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Peixoto de Azevedo', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Planalto da Serra', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Poconé', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Pontal do Araguaia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Ponte Branca', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Pontes e Lacerda', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Porto Alegre do Norte', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Porto dos Gaúchos', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Porto Esperidião', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Porto Estrela', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Poxoréo', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Primavera do Leste', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Querência', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Reserva do Cabaçal', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão Cascalheira', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirãozinho', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Rio Branco', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Rondolândia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Rondonópolis', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Rosário Oeste', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Salto do Céu', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Santa Carmem', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz do Xingu', 'estado_id' => '13', 'codigo_tce'  => '510774'],
            ['nome' => 'Santa Rita do Trivelato', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Santa Terezinha', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Santo Afonso', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Leste', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Leverger', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'São Félix do Araguaia', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'São José do Povo', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'São José do Rio Claro', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'São José do Xingu', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'São José dos Quatro Marcos', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro da Cipa', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Sapezal', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Serra Nova Dourada', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Sinop', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Sorriso', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Tabaporã', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Tangará da Serra', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Tapurah', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Terra Nova do Norte', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Tesouro', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Torixoréu', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'União do Sul', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Vale de São Domingos', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Várzea Grande', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Vera', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Vila Bela da Santíssima Trindade', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Vila Rica', 'estado_id' => '13', 'codigo_tce'  => ''],
            ['nome' => 'Água Clara', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Alcinópolis', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Amambaí', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Anastácio', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Anaurilândia', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Angélica', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Antônio João', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Aparecida do Taboado', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Aquidauana', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Aral Moreira', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Bandeirantes', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Bataguassu', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Bataiporã', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Bela Vista', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Bodoquena', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Bonito', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Brasilândia', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Caarapó', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Camapuã', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Campo Grande', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Caracol', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Cassilândia', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Chapadão do Sul', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Corguinho', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Sapucaia', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Corumbá', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Costa Rica', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Coxim', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Deodápolis', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Dois Irmãos do Buriti', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Douradina', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Dourados', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Eldorado', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Fátima do Sul', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Figueirão', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Glória de Dourados', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Guia Lopes da Laguna', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Iguatemi', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Inocência', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Itaporã', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Itaquiraí', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Ivinhema', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Japorã', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Jaraguari', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Jardim', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Jateí', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Juti', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Ladário', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Laguna Carapã', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Maracaju', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Miranda', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Mundo Novo', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Naviraí', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Nioaque', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Nova Alvorada do Sul', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Nova Andradina', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Novo Horizonte do Sul', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Paranaíba', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Paranhos', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Pedro Gomes', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Ponta Porã', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Porto Murtinho', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Ribas do Rio Pardo', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Rio Brilhante', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Rio Negro', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Rio Verde de Mato Grosso', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Rochedo', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita do Pardo', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'São Gabriel do Oeste', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Selvíria', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Sete Quedas', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Sidrolândia', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Sonora', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Tacuru', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Taquarussu', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Terenos', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Três Lagoas', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Vicentina', 'estado_id' => '12', 'codigo_tce'  => ''],
            ['nome' => 'Abadia dos Dourados', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Abaeté', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Abre Campo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Acaiaca', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Açucena', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Água Boa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Água Comprida', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Aguanil', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Águas Formosas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Águas Vermelhas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Aimorés', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Aiuruoca', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alagoa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Albertina', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Além Paraíba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alfenas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alfredo Vasconcelos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Almenara', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alpercata', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alpinópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alterosa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alto Caparaó', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alto Jequitibá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alto Rio Doce', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alvarenga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alvinópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Alvorada de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Amparo do Serra', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Andradas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Andrelândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Angelândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Antônio Carlos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Antônio Dias', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Antônio Prado de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Araçaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Aracitaba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Araçuaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Araguari', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Arantina', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Araponga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Araporã', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Arapuá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Araújos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Araxá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Arceburgo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Arcos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Areado', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Argirita', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Aricanduva', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Arinos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Astolfo Dutra', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ataléia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Augusto de Lima', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Baependi', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Baldim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bambuí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bandeira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bandeira do Sul', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Barão de Cocais', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Barão de Monte Alto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Barbacena', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Barra Longa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Barroso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bela Vista de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Belmiro Braga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Belo Horizonte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Belo Oriente', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Belo Vale', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Berilo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Berizal', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bertópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Betim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bias Fortes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bicas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Biquinhas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Boa Esperança', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bocaina de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bocaiúva', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bom Despacho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jardim de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus da Penha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus do Amparo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus do Galho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bom Repouso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bom Sucesso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bonfim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bonfinópolis de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bonito de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Borda da Mata', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Botelhos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Botumirim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Brás Pires', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Brasilândia de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Brasília de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Brasópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Braúnas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Brumadinho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bueno Brandão', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Buenópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Bugre', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Buritis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Buritizeiro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cabeceira Grande', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cabo Verde', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeira da Prata', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeira de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeira de Pajeú', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeira Dourada', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caetanópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caeté', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caiana', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cajuri', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caldas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Camacho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Camanducaia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cambuí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cambuquira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campanário', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campanha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campestre', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campina Verde', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campo Azul', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campo Belo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campo do Meio', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campo Florido', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campos Altos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Campos Gerais', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cana Verde', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Canaã', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Canápolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Candeias', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cantagalo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caparaó', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Capela Nova', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Capelinha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Capetinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Capim Branco', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Capinópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Capitão Andrade', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Capitão Enéas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Capitólio', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caputira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caraí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caranaíba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carandaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carangola', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caratinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carbonita', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Careaçu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carlos Chagas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carmésia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carmo da Cachoeira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carmo da Mata', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carmo de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carmo do Cajuru', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carmo do Paranaíba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carmo do Rio Claro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carmópolis de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carneirinho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carrancas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carvalhópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Carvalhos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Casa Grande', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cascalho Rico', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cássia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cataguases', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Catas Altas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Catas Altas da Noruega', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Catuji', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Catuti', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Caxambu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cedro do Abaeté', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Central de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Centralina', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Chácara', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Chalé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Chapada do Norte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Chapada Gaúcha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Chiador', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cipotânea', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Claraval', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Claro dos Poções', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cláudio', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coimbra', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coluna', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Comendador Gomes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Comercinho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conceição da Aparecida', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conceição da Barra de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conceição das Alagoas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conceição das Pedras', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conceição de Ipanema', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conceição do Mato Dentro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conceição do Pará', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conceição do Rio Verde', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conceição dos Ouros', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cônego Marinho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Confins', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Congonhal', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Congonhas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Congonhas do Norte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conquista', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conselheiro Lafaiete', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Conselheiro Pena', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Consolação', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Contagem', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coqueiral', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coração de Jesus', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cordisburgo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cordislândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Corinto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coroaci', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coromandel', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Fabriciano', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Murta', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Pacheco', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Coronel Xavier Chaves', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Córrego Danta', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Córrego do Bom Jesus', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Córrego Fundo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Córrego Novo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Couto de Magalhães de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Crisólita', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cristais', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cristália', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cristiano Otoni', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cristina', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Crucilândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cruzeiro da Fortaleza', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cruzília', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Cuparaque', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Curral de Dentro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Curvelo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Datas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Delfim Moreira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Delfinópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Delta', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Descoberto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Desterro de Entre Rios', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Desterro do Melo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Diamantina', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Diogo de Vasconcelos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dionísio', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Divinésia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Divino', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Divino das Laranjeiras', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Divinolândia de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Divinópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Divisa Alegre', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Divisa Nova', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Divisópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dom Bosco', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dom Cavati', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dom Joaquim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dom Silvério', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dom Viçoso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dona Eusébia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dores de Campos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dores de Guanhães', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dores do Indaiá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Dores do Turvo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Doresópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Douradoquara', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Durandé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Elói Mendes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Engenheiro Caldas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Engenheiro Navarro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Entre Folhas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Entre Rios de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ervália', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Esmeraldas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Espera Feliz', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Espinosa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Espírito Santo do Dourado', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Estiva', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Estrela Dalva', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Estrela do Indaiá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Estrela do Sul', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Eugenópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ewbank da Câmara', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Extrema', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Fama', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Faria Lemos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Felício dos Santos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Felisburgo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Felixlândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Fernandes Tourinho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ferros', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Fervedouro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Florestal', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Formiga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Formoso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Fortaleza de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Fortuna de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Badaró', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Dumont', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Francisco Sá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Franciscópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Frei Gaspar', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Frei Inocêncio', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Frei Lagonegro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Fronteira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Fronteira dos Vales', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Fruta de Leite', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Frutal', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Funilândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Galiléia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Gameleiras', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Glaucilândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Goiabeira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Goianá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Gonçalves', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Gonzaga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Gouveia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Governador Valadares', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Grão Mogol', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Grupiara', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guanhães', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guapé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guaraciaba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guaraciama', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guaranésia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guarani', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guarará', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guarda-Mor', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guaxupé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guidoval', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guimarânia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Guiricema', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Gurinhatã', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Heliodora', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Iapu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ibertioga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ibiá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ibiaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ibiracatu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ibiraci', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ibirité', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ibitiúra de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ibituruna', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Icaraí de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Igarapé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Igaratinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Iguatama', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ijaci', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ilicínea', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Imbé de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Inconfidentes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Indaiabira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Indianópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ingaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Inhapim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Inhaúma', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Inimutaba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ipaba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ipanema', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ipatinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ipiaçu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ipuiúna', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Iraí de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itabira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itabirinha de Mantena', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itabirito', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itacambira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itacarambi', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itaguara', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itaipé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itajubá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itamarandiba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itamarati de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itambacuri', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itambé do Mato Dentro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itamogi', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itamonte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itanhandu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itanhomi', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itaobim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itapagipe', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itapecerica', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itapeva', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itatiaiuçu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itaú de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itaúna', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itaverava', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itueta', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ituiutaba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itumirim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Iturama', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Itutinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jaboticatubas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jacinto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jacuí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jacutinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jaguaraçu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jaíba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jampruca', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Janaúba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Januária', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Japaraíba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Japonvar', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jeceaba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jenipapo de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jequeri', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jequitaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jequitibá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jequitinhonha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jesuânia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Joaíma', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Joanésia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'João Monlevade', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'João Pinheiro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Joaquim Felício', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Jordânia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'José Gonçalves de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'José Raydan', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Josenópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Juatuba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Juiz de Fora', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Juramento', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Juruaia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Juvenília', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ladainha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lagamar', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa da Prata', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa dos Patos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Dourada', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Formosa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Grande', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lagoa Santa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lajinha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lambari', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lamim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Laranjal', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lassance', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lavras', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Leandro Ferreira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Leme do Prado', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Leopoldina', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Liberdade', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lima Duarte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Limeira do Oeste', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Lontra', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Luisburgo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Luislândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Luminárias', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Luz', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Machacalis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Machado', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Madre de Deus de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Malacacheta', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mamonas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Manga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Manhuaçu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Manhumirim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mantena', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mar de Espanha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Maravilhas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Maria da Fé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mariana', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Marilac', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mário Campos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Maripá de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Marliéria', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Marmelópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Martinho Campos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Martins Soares', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mata Verde', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Materlândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mateus Leme', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mathias Lobato', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Matias Barbosa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Matias Cardoso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Matipó', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mato Verde', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Matozinhos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Matutina', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Medeiros', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Medina', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mendes Pimentel', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mercês', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mesquita', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Minas Novas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Minduri', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mirabela', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Miradouro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Miraí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Miravânia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Moeda', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Moema', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Monjolos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Monsenhor Paulo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Montalvânia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Monte Alegre de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Monte Azul', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Monte Belo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Monte Carmelo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Monte Formoso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Monte Santo de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Monte Sião', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Montes Claros', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Montezuma', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Morada Nova de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Morro da Garça', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Morro do Pilar', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Munhoz', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Muriaé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Mutum', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Muzambinho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nacip Raydan', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nanuque', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Naque', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Natalândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Natércia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nazareno', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nepomuceno', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ninheira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nova Belém', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nova Era', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nova Lima', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nova Módica', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nova Ponte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nova Porteirinha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nova Resende', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nova Serrana', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Nova União', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Novo Cruzeiro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Novo Oriente de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Novorizonte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Olaria', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Olhos-d`Água', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Olímpio Noronha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Oliveira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Oliveira Fortes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Onça de Pitangui', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Oratórios', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Orizânia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Branco', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Fino', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Preto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ouro Verde de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Padre Carvalho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Padre Paraíso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pai Pedro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Paineiras', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pains', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Paiva', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Palma', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Palmópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Papagaios', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pará de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Paracatu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Paraguaçu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Paraisópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Paraopeba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Passa Quatro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Passa Tempo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Passabém', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Passa-Vinte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Passos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Patis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Patos de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Patrocínio', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Patrocínio do Muriaé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Paula Cândido', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Paulistas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pavão', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Peçanha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Azul', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Bonita', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedra do Anta', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedra do Indaiá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedra Dourada', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedralva', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedras de Maria da Cruz', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedrinópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedro Leopoldo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pedro Teixeira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pequeri', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pequi', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Perdigão', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Perdizes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Perdões', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Periquito', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pescador', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piau', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piedade de Caratinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piedade de Ponte Nova', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piedade do Rio Grande', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piedade dos Gerais', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pimenta', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pingo-dÁgua', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pintópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piracema', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pirajuba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piranga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piranguçu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piranguinho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pirapetinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pirapora', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piraúba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pitangui', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Piumhi', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Planura', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Poço Fundo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Poços de Caldas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pocrane', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pompéu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ponte Nova', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ponto Chique', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ponto dos Volantes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Porteirinha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Porto Firme', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Poté', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pouso Alegre', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pouso Alto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Prados', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Prata', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pratápolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Pratinha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Bernardes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Juscelino', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Kubitschek', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Presidente Olegário', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Prudente de Morais', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Quartel Geral', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Queluzito', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Raposos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Raul Soares', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Recreio', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Reduto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Resende Costa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Resplendor', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ressaquinha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Riachinho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Riacho dos Machados', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão das Neves', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ribeirão Vermelho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Acima', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Casca', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio do Prado', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Doce', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Espera', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Manso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Novo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Paranaíba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Pardo de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Piracicaba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Pomba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Preto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rio Vermelho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ritápolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rochedo de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rodeiro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Romaria', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rosário da Limeira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rubelita', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Rubim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sabará', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sabinópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sacramento', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Salinas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Salto da Divisa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Bárbara', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Bárbara do Leste', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Bárbara do Monte Verde', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Bárbara do Tugúrio', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz de Salinas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Cruz do Escalvado', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Efigênia de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Fé de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Helena de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Juliana', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Luzia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Margarida', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria de Itabira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria do Salto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Maria do Suaçuí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita de Caldas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita de Ibitipoca', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita de Jacutinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita do Itueto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rita do Sapucaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Rosa da Serra', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santa Vitória', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana da Vargem', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana de Cataguases', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana de Pirapama', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Deserto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Garambéu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Jacaré', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Manhuaçu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Paraíso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana do Riacho', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santana dos Montes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Amparo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Aventureiro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Grama', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Itambé', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Jacinto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Monte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Retiro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santo Antônio do Rio Abaixo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santo Hipólito', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Santos Dumont', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Bento Abade', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Brás do Suaçuí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos das Dores', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Domingos do Prata', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Félix de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco de Paula', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco de Sales', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Francisco do Glória', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Geraldo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Geraldo da Piedade', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Geraldo do Baixio', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Gonçalo do Abaeté', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Gonçalo do Pará', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Gonçalo do Rio Abaixo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Gonçalo do Rio Preto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Gonçalo do Sapucaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Gotardo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João Batista do Glória', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João da Lagoa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João da Mata', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João da Ponte', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João das Missões', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João del Rei', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João do Manhuaçu', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João do Manteninha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João do Oriente', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João do Pacuí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João do Paraíso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João Evangelista', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São João Nepomuceno', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Joaquim de Bicas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São José da Barra', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São José da Lapa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São José da Safira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São José da Varginha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São José do Alegre', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São José do Divino', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São José do Goiabal', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São José do Jacuri', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São José do Mantimento', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Lourenço', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Miguel do Anta', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro da União', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro do Suaçuí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Pedro dos Ferros', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Romão', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Roque de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião da Bela Vista', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião da Vargem Alegre', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Anta', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Maranhão', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Oeste', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Paraíso', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Rio Preto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Sebastião do Rio Verde', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Thomé das Letras', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Tiago', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Tomás de Aquino', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'São Vicente de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sapucaí-Mirim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sardoá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sarzedo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sem-Peixe', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Senador Amaral', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Senador Cortes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Senador Firmino', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Senador José Bento', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Senador Modestino Gonçalves', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Senhora de Oliveira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Senhora do Porto', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Senhora dos Remédios', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sericita', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Seritinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Serra Azul de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Serra da Saudade', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Serra do Salitre', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Serra dos Aimorés', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Serrania', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Serranópolis de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Serranos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Serro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sete Lagoas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Setubinha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Silveirânia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Silvianópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Simão Pereira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Simonésia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Sobrália', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Soledade de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tabuleiro', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Taiobeiras', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Taparuba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tapira', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tapiraí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Taquaraçu de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tarumirim', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Teixeiras', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Teófilo Otoni', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Timóteo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tiradentes', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tiros', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tocantins', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tocos do Moji', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Toledo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tombos', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Três Corações', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Três Marias', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Três Pontas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tumiritinga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Tupaciguara', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Turmalina', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Turvolândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ubá', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ubaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Ubaporanga', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Uberaba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Uberlândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Umburatiba', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Unaí', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'União de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Uruana de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Urucânia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Urucuia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Vargem Alegre', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Vargem Bonita', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Vargem Grande do Rio Pardo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Varginha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Varjão de Minas', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Várzea da Palma', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Varzelândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Vazante', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Verdelândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Veredinha', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Veríssimo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Vermelho Novo', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Vespasiano', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Viçosa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Vieiras', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Virgem da Lapa', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Virgínia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Virginópolis', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Virgolândia', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Visconde do Rio Branco', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Volta Grande', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Wenceslau Braz', 'estado_id' => '11', 'codigo_tce'  => ''],
            ['nome' => 'Abaetetuba', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Abel Figueiredo', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Acará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Afuá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Água Azul do Norte', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Alenquer', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Almeirim', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Altamira', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Anajás', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Ananindeua', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Anapu', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Augusto Corrêa', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Aurora do Pará', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Aveiro', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Bagre', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Baião', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Bannach', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Barcarena', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Belém', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Belterra', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Benevides', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Bom Jesus do Tocantins', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Bonito', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Bragança', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Brasil Novo', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Brejo Grande do Araguaia', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Breu Branco', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Breves', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Bujaru', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeira do Arari', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Cachoeira do Piriá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Cametá', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Canaã dos Carajás', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Capanema', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Capitão Poço', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Castanhal', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Chaves', 'estado_id' => '14', 'codigo_tce'  => ''],
            ['nome' => 'Colares', 'estado_id' => '14', 'codigo_tce'  => ''],


        ]);

    }
}
